export enum Stat {
  // Protection
  ARMOR = "ARMOR",
  WILLPOWER = "WILLPOWER",
  EVASION = "EVASION",
  PARRY = "PARRY",
  ELEMENTAL_RESIST = "ELEMENTAL_RESIST",
  PHYSICAL_RESIST = "PHYSICAL_RESIST",

  // Attaque
  PHYSICAL_DAMAGE = "PHYSICAL_DAMAGE",
  ELEMENTAL_DAMAGE = "ELEMENTAL_DAMAGE",
  PHYSICAL_AFFLICTION = "PHYSICAL_AFFLICTION",
  ELEMENTAL_AFFLICTION = "ELEMENTAL_AFFLICTION",
  CRIT_CHANCE = "CRIT_CHANCE",
  CRIT_DAMAGE = "CRIT_DAMAGE",
  HIT_CHANCE = "HIT_CHANCE",
  PHYSICAL_PENETRATION = "PHYSICAL_PENETRATION",
  ELEMENTAL_PENETRATION = "ELEMENTAL_PENETRATION",

  // Utilitaire
  HEALING_BONUS = "HEALING_BONUS",
  MAX_HEALTH = "MAX_HEALTH",
  MAX_MANA = "MAX_MANA",
  HEALTH_REGEN = "HEALTH_REGEN",
  MANA_REGEN = "MANA_REGEN",
  ELEMENTAL_SHIELD = "ELEMENTAL_SHIELD",
  SHIELD_REGEN = "SHIELD_REGEN",
  MOVEMENT_SPEED = "MOVEMENT_SPEED",
  COOLDOWN_RECOVERY = "COOLDOWN_RECOVERY"
}

export type ModifierType = "FLAT" | "PERCENT";

export interface StatModifier {
  value: number;
  type: ModifierType;
}

export type StatsMap = {
  [key in Stat]?: StatModifier;
};

export type BaseStatsMap = {
  [key in Stat]?: number;
};
